# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0074_auto_20180515_1215'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City'),
        ),
        migrations.AddField(
            model_name='user',
            name='go_out_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'employee')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
