# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0074_auto_20180515_1215'),
        ('users', '0003_auto_20180517_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_place_types',
            field=models.ManyToManyField(to='places.PlaceType'),
        ),
    ]
