# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0022_auto_20180413_1120'),
        ('users', '0004_user_favorite_place_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteChoiceFilterField',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Favorite')),
                ('value', models.ManyToManyField(to='filter.ChoiceFilterFieldOption')),
            ],
            bases=('users.favorite',),
        ),
        migrations.AddField(
            model_name='favorite',
            name='filter_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.FilterField'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
