# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180601_1400'),
        ('users', '0008_auto_20180603_1536'),
    ]

    operations = [
    ]
