# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import good_spot.users.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20180605_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=good_spot.users.models.avatars_folder),
        ),
    ]
