# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populartimes', '0002_populartimes_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populartimes',
            options={'verbose_name_plural': 'Populartimes'},
        ),
    ]
