# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populartimes', '0003_auto_20180507_1334'),
        ('populartimes', '0003_auto_20180515_1215'),
    ]

    operations = [
    ]
