# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 14:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180529_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
