# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180529_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(choices=[('terms', 'terms'), ('policy', 'policy')], unique=True),
        ),
    ]
