# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 12:56
from __future__ import unicode_literals

from django.db import migrations


def populate_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    # creating FAQ
    Page.objects.create(
        title='FAQ',
        slug='faq',
        text=' '
    )

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180530_0815'),
    ]

    operations = [
        migrations.RunPython(populate_pages),
    ]
