# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatingRuleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UpdatingRule', verbose_name='updating_rule')),
            ],
        ),
    ]
