# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatingrule',
            name='rule',
            field=models.CharField(choices=[('ONCE', 'Once'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('HOURLY', 'Hourly')], max_length=10, verbose_name='frequency'),
        ),
    ]
