# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180314_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatingrule',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='This rule will work until this date.', null=True, verbose_name='end'),
        ),
    ]
