# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_updatingrule_end'),
        ('places', '0065_auto_20180330_1202'),
    ]

    operations = [
    ]
