# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180315_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatingrule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
