# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 14:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_updatingrule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatingrule',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
