# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 14:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_updatingrule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatingrule',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MON'), (1, 'TUE'), (2, 'WED'), (3, 'THU'), (4, 'FRI'), (5, 'SAT'), (6, 'SUN')], null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
