# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 14:51
from __future__ import unicode_literals

from django.db import migrations


def populate_weekdays(apps, schema_editor):
    UpdatingRule = apps.get_model('events', 'UpdatingRule')
    for obj in UpdatingRule.objects.all():
        obj.weekday = obj.start.weekday()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180601_1451'),
    ]

    operations = [
        migrations.RunPython(populate_weekdays)
    ]
