# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180605_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatingrulerelation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_relations', to='events.UpdatingRule', verbose_name='updating_rule'),
        ),
    ]
