# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 07:29
from __future__ import unicode_literals

from django.db import migrations
from model_utils import Choices


def resave_rules(apps, schema_editor):
    WEEKDAY_DATETIME = {
        0: 'MON',
        1: 'TUE',
        2: 'WED',
        3: 'THU',
        4: 'FRI',
        5: 'SAT',
        6: 'SUN'
    }

    RULE = Choices(
        ("ONCE", "Once"),
        ("YEARLY", "Yearly"),
        ("MONTHLY", "Monthly"),
        ("WEEKLY", "Weekly"),
        ("DAILY", "Daily"),
        ("HOURLY", "Hourly"),
    )

    UpdatingRule = apps.get_model('events', 'UpdatingRule')
    for rule in UpdatingRule.objects.all():
        if rule.rule == RULE.WEEKLY:
            rule.title = "{} updating on {} at {}".format(
                rule.rule,
                WEEKDAY_DATETIME[rule.weekday],
                rule.start_time
            )
        else:
            rule.title = "{} updating at {}".format(rule.rule, rule.start_time)
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180608_0702'),
    ]

    operations = [
        migrations.RunPython(resave_rules)
    ]
