# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='external_ip',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
