# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20180209_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='external_ip',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
