# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20180209_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name_plural': 'Proxies'},
        ),
    ]
