# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180312_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
