# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 14:40
from __future__ import unicode_literals

from django.db import migrations


def reorder(apps, schema_editor):
    from django.core import management
    management.call_command('reorder', 'images.PlaceImage')


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180313_1438'),
    ]

    operations = [
        migrations.RunPython(reorder)
    ]
