# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place name')),
                ('google_place_id', models.CharField(max_length=255, unique=True, verbose_name='Place ID')),
                ('google_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place address')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('long_description', models.TextField(blank=True)),
                ('open_hours', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('populartimes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('google_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('place_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceType')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
