# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_types',
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.ManyToManyField(to='places.PlaceType'),
        ),
    ]
