# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 14:36
from __future__ import unicode_literals

from django.db import migrations


def add_place_type(apps, schema_editor):
    PlaceType = apps.get_model('places', 'PlaceType')
    place_types = ["Night Club", "Bar", "Restaurant"]
    for place_type in place_types:
        PlaceType.objects.create(name=place_type)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20171214_1413'),
    ]

    operations = [
        migrations.RunPython(add_place_type),
    ]
