# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Country')),
            ],
        ),
    ]
