# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:40
from __future__ import unicode_literals

from django.db import migrations


def update_place_type(apps, schema_editor):
    PlaceType = apps.get_model('places', 'PlaceType')
    PlaceType.objects.filter(name="Night Club").update(slug="night_club")
    PlaceType.objects.filter(name="Bar").update(slug="bar")
    PlaceType.objects.filter(name="Restaurant").update(slug="restaurant")


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20171219_1439'),
    ]

    operations = [
        migrations.RunPython(update_place_type),
    ]
