# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20171219_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='frequentation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
