# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place_frequentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
