# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_place_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
