# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_place_id_gay_friendly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id_gay_friendly',
            new_name='is_gay_friendly',
        ),
    ]
