# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20171219_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
