# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_remove_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_price_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
