# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 18:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_place_google_price_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='extended_place_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
