# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_fieldtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='field_type',
            field=models.CharField(choices=[('bool', 'boolean'), ('text', 'text'), ('multi', 'multiple choice'), ('choice', 'single choice')], max_length=6, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='placefield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.FieldType'),
        ),
        migrations.AddField(
            model_name='placefield',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
