# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20171225_1943'),
        ('places', '0020_place_extended_place_types'),
    ]

    operations = [
    ]
