# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 12:02
from __future__ import unicode_literals

from django.db import migrations


def update_locality(apps, schema_editor):
    City = apps.get_model('places', 'City')
    City.objects.filter(name='Kyiv').update(name_variants=['Киев', 'Київ', 'Kyiv city', 'Kiev', 'Kiyev', 'г. Киев'])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_city_name_variants'),
    ]

    operations = [
        migrations.RunPython(update_locality),
    ]
