# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20171224_1641'),
        ('places', '0024_auto_20171227_1202'),
    ]

    operations = [
    ]
