# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_merge_20171228_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together=set([('field_type', 'place')]),
        ),
    ]
