# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_auto_20171228_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='special_event',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special event'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_fields', to='places.Place'),
        ),
    ]
