# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_fieldtype_is_shown_in_about_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='is_disabled',
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='is_filter',
            field=models.BooleanField(default=False, help_text='Do you want to show this field in filter?', verbose_name='Is filter?'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='is_shown_in_about_place',
            field=models.BooleanField(default=False, help_text='Use this field to generate `About Place` section on detail screen.', verbose_name='Show in About Place section'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='is_shown_in_short_description',
            field=models.BooleanField(default=False, help_text='Use this field to generate `Short Description` section on detail screen.', verbose_name='Show in short description'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='place_type',
            field=models.ManyToManyField(help_text='This field will be available for choosen places types', to='places.PlaceType'),
        ),
    ]
