# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_auto_20171229_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='is_filter',
            field=models.BooleanField(default=False, help_text='Use this field to generate filters.', verbose_name='Is filter?'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='place_type',
            field=models.ManyToManyField(help_text='This field will be available for choosen places types.', to='places.PlaceType'),
        ),
    ]
