# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_auto_20171230_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='is_shown_in_features',
            field=models.BooleanField(default=False, help_text='Use this field to generate features displaying under the title of place.', verbose_name='Show in features'),
        ),
    ]
