# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_fieldtype_is_shown_in_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='block_address',
            field=models.BooleanField(default=False, help_text='Block Address from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_google_price_level',
            field=models.BooleanField(default=False, help_text='Block Google price level from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_google_rating',
            field=models.BooleanField(default=False, help_text='Block Google rating from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_location',
            field=models.BooleanField(default=False, help_text='Block Location from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_phone',
            field=models.BooleanField(default=False, help_text='Block Phone from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_place_types',
            field=models.BooleanField(default=False, help_text='Block Place types from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='block_website',
            field=models.BooleanField(default=False, help_text='Block Website from updating from the Google Places API'),
        ),
        migrations.AddField(
            model_name='place',
            name='update_populartimes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='field_type',
            field=models.CharField(choices=[('bool', 'boolean'), ('text', 'text'), ('multi', 'multiple choice'), ('choice', 'single choice')], help_text='For types `multiple choice` and `single choice`, please, provide data separated by comma.', max_length=6, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='place_type',
            field=models.ManyToManyField(help_text='This field will be available for choosen places types.', related_name='field_types', to='places.PlaceType'),
        ),
        migrations.AlterField(
            model_name='placefield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_fields', to='places.FieldType'),
        ),
    ]
