# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0032_auto_20171231_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetype',
            name='icon',
        ),
        migrations.AlterField(
            model_name='place',
            name='block_address',
            field=models.BooleanField(default=False, help_text="Block <b>Address</b> from updating from the Google Places API.<br>It means, if you change <b>Address</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_google_price_level',
            field=models.BooleanField(default=False, help_text="Block <b>Google price level</b> from updating from the Google Places API.<br>It means, if you change <b>Google price level</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_google_rating',
            field=models.BooleanField(default=False, help_text="Block <b>Google rating</b> from updating from the Google Places API.<br>It means, if you change <b>Google rating</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_location',
            field=models.BooleanField(default=False, help_text="Block <b>Location</b> from updating from the Google Places API.<br>It means, if you change <b>Location</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_phone',
            field=models.BooleanField(default=False, help_text="Block <b>Phone</b> from updating from the Google Places API.<br>It means, if you change <b>Phone</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_place_types',
            field=models.BooleanField(default=False, help_text="Block <b>Place types</b> from updating from the Google Places API.<br>It means, if you change <b>Place types</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
        migrations.AlterField(
            model_name='place',
            name='block_website',
            field=models.BooleanField(default=False, help_text="Block <b>Website</b> from updating from the Google Places API.<br>It means, if you change <b>Website</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
    ]
