# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_placetype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default to show in main screen?'),
        ),
    ]
