# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0035_placetype_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=10, null=True, verbose_name='Slug'),
        ),
    ]
