# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0036_auto_20180124_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'ordering': ['order'], 'verbose_name': 'Filter field', 'verbose_name_plural': 'Filter fields'},
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
