# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0039_auto_20180129_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualPopularTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('actual_pop_times', django.contrib.postgres.fields.jsonb.JSONField()),
                ('expire_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
