# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0040_actualpopulartimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.PositiveSmallIntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequentations', to='places.Place')),
            ],
            options={
                'ordering': ('place', '-created'),
            },
        ),
    ]
