# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0041_frequentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='frequentation',
        ),
    ]
