# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0042_remove_place_frequentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualpopulartimes',
            old_name='actual_pop_times',
            new_name='value',
        ),
    ]
