# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0043_auto_20180130_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='actual_populartimes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.ActualPopularTimes'),
        ),
    ]
