# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0044_place_actual_populartimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='actual_populartimes',
        ),
    ]
