# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 21:18
from __future__ import unicode_literals

from django.db import migrations

from structlog import get_logger

log = get_logger()


def update_timezone_for_city(apps, schema_editor):
    City = apps.get_model('places', 'City')
    city_timezone_mapping = (
        ('Kyiv', 'Europe/Kiev'),
        ('Paris', 'Europe/Paris')
    )
    for city_tz in city_timezone_mapping:
        try:
            City.objects.filter(name=city_tz[0]).update(timezone=city_tz[1])
        except Exception as e:
            log = log.bind(
                city_tz=city_tz
            )
            log.error('Error when tries to update timezone.')


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0048_auto_20180131_2110'),
    ]

    operations = [
        migrations.RunPython(update_timezone_for_city),
    ]
