# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0051_place_block_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='block_name',
            field=models.BooleanField(default=False, help_text="Block <b>Place name</b> from updating from the Google Places API.<br>It means, if you change <b>Place name</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
    ]
