# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0052_auto_20180209_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
    ]
