# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0053_auto_20180212_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='populartimes_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=django.db.models.fields.DateTimeField),
        ),
    ]
