# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 17:48
from __future__ import unicode_literals

from django.contrib.postgres.fields import JSONField
from django.db import migrations
from django.db.models import F, ExpressionWrapper


def update_place_fields(apps, schema_editor):
    PlaceField = apps.get_model('places', 'PlaceField')
    for place_field in PlaceField.objects.filter(field_type__field_type='choice'):
        place_field.value = [place_field.value]
        place_field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0055_city_is_active'),
    ]

    operations = [
        migrations.RunPython(update_place_fields)
    ]
