# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 19:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0056_auto_20180221_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
