# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 19:58
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0057_place_short_description'),
    ]

    operations = [
    ]
