# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0059_place_features'),
    ]

    operations = [
    ]
