# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0060_auto_20180313_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Place type'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='name_fr',
            field=models.CharField(max_length=20, null=True, verbose_name='Place type'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Place type'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='name_uk',
            field=models.CharField(max_length=20, null=True, verbose_name='Place type'),
        ),
    ]
