# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0061_auto_20180330_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place address'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place address'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place address'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place address'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AddField(
            model_name='place',
            name='special_event_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special event'),
        ),
        migrations.AddField(
            model_name='place',
            name='special_event_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special event'),
        ),
        migrations.AddField(
            model_name='place',
            name='special_event_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special event'),
        ),
        migrations.AddField(
            model_name='place',
            name='special_event_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Special event'),
        ),
    ]
