# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0062_auto_20180330_0714'),
    ]

    operations = [
    ]
