# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 12:02
from __future__ import unicode_literals

from django.db import migrations


def populate_cities_countries(apps, schema_editor):
    City = apps.get_model('places', 'City')

    for city in City.objects.all():
        City.objects.filter(
            id=city.id
        ).update(
            name=city.city.name,
            country_name=city.city.country.name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0064_auto_20180330_1211'),
    ]

    operations = [
        migrations.RunPython(populate_cities_countries)
    ]
