# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0067_auto_20180330_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_name',
            field=models.CharField(blank=True, help_text='Will be autopopulated.', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_en',
            field=models.CharField(blank=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_fr',
            field=models.CharField(blank=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_ru',
            field=models.CharField(blank=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name_uk',
            field=models.CharField(blank=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Will be autopopulated.', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_fr',
            field=models.CharField(blank=True, db_index=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_uk',
            field=models.CharField(blank=True, db_index=True, help_text='Will be autopopulated.', max_length=200, null=True),
        ),
    ]
