# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 11:38
from __future__ import unicode_literals

from django.contrib.gis.geos import Point
from django.db import migrations


def populate_cities_coordinates(apps, schema_editor):
    City = apps.get_model("places", "City")
    for city in City.objects.all():
        City.objects.filter(id=city.id).update(
            point=Point(
                float(city.city.longitude),
                float(city.city.latitude)
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0071_city_point'),
    ]

    operations = [
        migrations.RunPython(populate_cities_coordinates)
    ]
