# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 11:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0072_auto_20180402_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
