# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 13:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0073_auto_20180402_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
