# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0073_auto_20180402_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='place_type',
        ),
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='placefield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='placefield',
            name='place',
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
        migrations.DeleteModel(
            name='PlaceField',
        ),
    ]
