# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0076_auto_20180606_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='active_in_cities',
            field=models.ManyToManyField(blank=True, to='places.City'),
        ),
    ]
