# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0078_auto_20180611_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentation',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequentation',
            name='origin_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
