# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0080_frequentation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='If checked this city will default in application in case when user dissalow GPS.'),
        ),
    ]
