# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0081_city_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='If checked this city will default in application in case when user disallowed GPS.'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_fr',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_uk',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Place name'),
        ),
    ]
