# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0082_auto_20180625_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualpopulartimes',
            options={'verbose_name_plural': 'Actual popular times'},
        ),
    ]
