# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0083_auto_20180702_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='block_city',
            field=models.BooleanField(default=False, help_text="Block <b>City</b> from updating from the Google Places API.<br>It means, if you change <b>City</b> manually, it won't be rewritten from the Google Places API after updating."),
        ),
    ]
