# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0084_place_block_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='name_plural',
            field=models.CharField(blank=True, max_length=20, verbose_name='Place type'),
        ),
    ]
