# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-01 10:35
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0087_auto_20180813_1226'),
    ]

    operations = [
        UnaccentExtension()
    ]
