# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolFilterField',
            fields=[
                ('filterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filter.FilterField')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('filter.filterfield',),
        ),
        migrations.CreateModel(
            name='ChoiceFilterField',
            fields=[
                ('filterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filter.FilterField')),
                ('is_multi', models.BooleanField(default=False)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('filter.filterfield',),
        ),
        migrations.CreateModel(
            name='TextFilterField',
            fields=[
                ('filterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filter.FilterField')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('filter.filterfield',),
        ),
    ]
