# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_placefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefield',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
