# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_placefield_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placefield',
            name='value',
        ),
        migrations.AddField(
            model_name='placefield',
            name='value',
            field=models.ManyToManyField(to='filter.ChoiceFilterFieldOption'),
        ),
    ]
