# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20180321_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterfield',
            options={'verbose_name': '_Filter field'},
        ),
        migrations.AddField(
            model_name='filterfield',
            name='is_filter',
            field=models.BooleanField(default=False, help_text='Use this field to generate filters.', verbose_name='Is filter?'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public?'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='is_shown_in_about_place',
            field=models.BooleanField(default=False, help_text='Use this field to generate `About Place` section on detail screen.', verbose_name='Show in About Place section'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='is_shown_in_features',
            field=models.BooleanField(default=False, help_text='Use this field to generate features displaying under the title of place.', verbose_name='Show in features'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='is_shown_in_short_description',
            field=models.BooleanField(default=False, help_text='Use this field to generate `Short Description` section on detail screen.', verbose_name='Show in short description'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='choicefilterfieldoption',
            name='choice_filter_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_options', to='filter.ChoiceFilterField'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='place_type',
            field=models.ManyToManyField(help_text='This field will be available for chosen places types.', to='places.PlaceType'),
        ),
    ]
