# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0007_auto_20180322_0959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choicefilterfieldoption',
            unique_together=set([('choice_filter_field', 'option')]),
        ),
    ]
