# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0060_auto_20180313_0938'),
        ('filter', '0009_auto_20180322_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterfield',
            options={'ordering': ('order',), 'verbose_name': '_Filter field'},
        ),
        migrations.AlterField(
            model_name='placefield',
            name='value',
            field=models.ManyToManyField(blank=True, to='filter.ChoiceFilterFieldOption'),
        ),
        migrations.AlterUniqueTogether(
            name='placefield',
            unique_together=set([('place', 'field_type')]),
        ),
    ]
