# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0011_placefilterfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceChoiceFilterField',
            fields=[
                ('placefilterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filter.PlaceFilterField')),
                ('value', models.ManyToManyField(blank=True, to='filter.ChoiceFilterFieldOption')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('filter.placefilterfield',),
        ),
    ]
