# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0016_auto_20180328_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boolfilterfield',
            options={'verbose_name': 'Fields BOOLEAN', 'verbose_name_plural': 'Fields BOOLEAN'},
        ),
        migrations.AlterModelOptions(
            name='choicefilterfield',
            options={'verbose_name': 'Fields SELECTIVE', 'verbose_name_plural': 'Fields SELECTIVE'},
        ),
        migrations.AlterModelOptions(
            name='filterfield',
            options={'ordering': ('order',), 'verbose_name': 'ALL FILTERS----------------------------------------------------', 'verbose_name_plural': 'ALL FILTERS----------------------------------------------------'},
        ),
        migrations.AlterModelOptions(
            name='placeboolfilterfield',
            options={'verbose_name': 'Place fields BOOLEAN', 'verbose_name_plural': 'Place fields BOOLEAN'},
        ),
        migrations.AlterModelOptions(
            name='placechoicefilterfield',
            options={'verbose_name': 'Place fields SELECTIVE', 'verbose_name_plural': 'Place fields SELECTIVE'},
        ),
        migrations.AlterModelOptions(
            name='placefilterfield',
            options={'verbose_name': 'PLACE FIELDS--------------------------------------------------', 'verbose_name_plural': 'PLACE FIELDS--------------------------------------------------'},
        ),
        migrations.AlterModelOptions(
            name='placetextfilterfield',
            options={'verbose_name': 'Place fields TEXTUAL', 'verbose_name_plural': 'Place fields TEXTUAL'},
        ),
        migrations.AlterModelOptions(
            name='textfilterfield',
            options={'verbose_name': 'Fields TEXTUAL', 'verbose_name_plural': 'Fields TEXTUAL'},
        ),
    ]
