# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0018_auto_20180329_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterfield',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='filterfield',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
