# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0019_auto_20180329_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicefilterfieldoption',
            name='option_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choicefilterfieldoption',
            name='option_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choicefilterfieldoption',
            name='option_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choicefilterfieldoption',
            name='option_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
