# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0021_auto_20180329_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicefilterfieldoption',
            options={'ordering': ('option',)},
        ),
    ]
