# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0023_filterfield_is_users_tastes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterfield',
            name='is_users_tastes',
        ),
    ]
