# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0024_remove_filterfield_is_users_tastes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicefilterfield',
            name='is_users_tastes',
            field=models.BooleanField(default=False, help_text='If checked user will see the section named as this filter field with options to choose his own tastes.', verbose_name='Lets user to choose his tastes in profile.'),
        ),
    ]
