# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0025_choicefilterfield_is_users_tastes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicefilterfield',
            name='is_multi',
            field=models.BooleanField(default=False, help_text='If you mark this field as `multi` user can select more then one choice in the Filter in the app.'),
        ),
    ]
